# Generated by Django 3.1.7 on 2021-05-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuser',
            name='country',
            field=models.CharField(blank=True, choices=[('india', 'india'), ('japan', 'japan'), ('china', 'china')], default='india', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50, null=True),
        ),
    ]
